### ISSUE TITLE
What is delta p?

### ISSUE THREAD

**Issue by DarwinCV** [kongaevans/Predicting-Renewal-Pay-of-Insurance#1]
hello kongkip, thanks for posting your repo publicly. I found your analysis very interesting and it helped me to give me ideas on how to approach a similar problem. The only doubt I have is what "delta p" means. That formula comes from a book or did you develop it? and how is it related to the incentive?

**Comment by kongkip** [comment]
Hi too,
The given problem was from a competition. The formula was provided but in
terms of a curve so the delta is a change of incentive with hours of
effort.
You can check the formula in this
<https://github.com/kongkip/Predicting-Renewal-Pay-of-Insurance/blob/master/img/given_formulas.png>
image
